import { Metadata } from "next";
import { NewsletterSection } from "@/components/home/NewsletterSection";

import DynamicArticle, { ArticleSection } from "@/components/shared/DynamicArticle";
import RelatedArticles from "@/components/shared/RelatedArticles";
export const metadata: Metadata = {
  title: "Jewellery Availability & Production Time Explained",
  description: "Learn the difference between in-stock, waitlist, preorder and made-to-order jewellery, how production time differs from delivery time, and what to confirm before ordering.",
  alternates: { canonical: "https://www.aureliaroyale.com/blog/jewellery-availability-production-time/" },
};
const articleSections: ArticleSection[] = [
  { content: [{ type: "paragraph", text: "When a jewellery product appears online, it does not necessarily mean the finished piece is sitting in stock ready for immediate dispatch. Fine jewellery can be offered in several different ways. One item may already exist and be available now. Another may be produced only after an order is placed. A future collection may be offered through preorder. A design that is not currently available may simply allow customers to join a waitlist or submit an enquiry." }, { type: "paragraph", text: "Those situations are commercially different, and the wording matters. The most important distinction is this: joining a waitlist is not the same as placing a preorder, and placing a preorder is not necessarily the same as commissioning made-to-order jewellery. Each stage creates different expectations around payment, production, delivery and whether an actual order or contract exists." }] },
  { heading: "Quick Answer: What Do Jewellery Availability Terms Mean?", content: [{ type: "paragraph", text: "Available now generally means a finished item or applicable stock is currently available for sale, subject to the retailer's actual inventory. Waitlist means you are asking to be contacted or notified about future availability. Unless the retailer expressly establishes otherwise, joining a waitlist should not be treated as an order, reservation or preorder. Preorder generally means the retailer is accepting actual orders for an item that will be supplied later rather than immediately. Made to order usually means production of the jewellery begins after the customer's order is accepted. Custom or personalised jewellery may involve changes created specifically for the customer and can have different cancellation implications from standard products." }, { type: "paragraph", text: "The practical question is therefore not simply: \"Is this jewellery available?\" It is: \"What stage is this product at, and what commitment am I making if I continue?\"" }] },
  { heading: "Jewellery Availability Is Not One Status", content: [{ type: "paragraph", text: "Ecommerce language can make several different situations look similar. A product page might contain a design, images and an enquiry button even when no finished item is currently available. Another product may be fully manufactured but waiting for a particular size selection. Another may require several production steps after an order. Another may not yet be accepting orders at all. That is why jewellery availability should be described more precisely than simply: Available or: Unavailable." }] },
  { heading: "What Does \"In Stock\" Mean?", content: [{ type: "paragraph", text: "For consumers, in stock normally creates a reasonable expectation that an item exists in available inventory. But even that term needs context. A ring may exist only in one size. A necklace may be available in one metal but not another. If jewellery is described as in stock, the retailer should avoid wording that implies every possible variation is immediately available unless that is actually true. For high-value jewellery, useful availability information might distinguish between: finished piece available and: design available but production required. Those are different customer expectations." }] },
  { heading: "Does In Stock Mean Same-Day Dispatch?", content: [{ type: "paragraph", text: "No. Availability and dispatch speed are separate questions. A finished item can be available while still requiring: quality checking; sizing; documentation preparation; or normal order processing. If timing matters, check the stated dispatch and delivery information separately." }] },
  { heading: "What Does \"Ready to Ship\" Mean?", content: [{ type: "paragraph", text: "\"Ready to ship\" is stronger than a general availability statement because it suggests production is already complete. But it still does not necessarily mean the customer will receive the jewellery the next day. There may still be: order processing; payment verification; dispatch preparation; courier collection; and transit time. So even where \"ready to ship\" is accurate, the product page should not allow buyers to confuse it with guaranteed next-day delivery unless a specific delivery service actually supports that promise." }] },
  { heading: "What Is a Jewellery Waitlist?", content: [{ type: "paragraph", text: "A waitlist is usually the lowest-commitment availability status. The customer provides contact details because they want to hear when: a design becomes available; new stock arrives; ordering opens; pricing is confirmed; or more information becomes available. The key point is that the customer is expressing interest. Unless the retailer clearly creates something more, a waitlist submission should not be represented as: an order; a reservation; a confirmed allocation; a preorder; or a payment obligation." }, { type: "paragraph", text: "For Aurelia, this distinction is essential. If a visitor enters an email address into a Join Waitlist form, the safest wording is that Aurelia may contact them when further information or availability becomes available. The form should not suggest that the customer has secured the jewellery unless the client has established an actual reservation process." }] },
  { heading: "What Should Happen After Joining a Waitlist?", content: [{ type: "paragraph", text: "A waitlist confirmation can say that the customer's interest has been recorded. It can also explain that Aurelia may contact them regarding availability. It should not say: Your order is confirmed; Your item has been reserved; Your preorder is successful; or: Your jewellery is now in production unless one of those things has genuinely happened. That distinction protects both customer expectations and the accuracy of the website." }] },
  { heading: "Is a Waitlist the Same as a Reservation?", content: [{ type: "paragraph", text: "No, not automatically. A reservation suggests that a particular item, production slot or allocation is being held for a customer. A waitlist normally means the customer is waiting for an opportunity to purchase or receive more information. If Aurelia eventually introduces a reservation system, it should have separate terms explaining: what is reserved; for how long; whether payment is required; and what happens if the customer does not proceed. Until then: Join Waitlist = register interest." }] },
  { heading: "What Is a Jewellery Preorder?", content: [{ type: "paragraph", text: "A preorder is more substantial than a waitlist. In ordinary ecommerce use, preorder means the retailer is accepting an actual order now for supply at a later date. The item may not yet be ready for dispatch. The important difference is that a preorder generally involves an ordering process rather than simply collecting an email address. If payment is required, that obligation needs to be made clear." }, { type: "paragraph", text: "Current UK online-selling guidance states that the final ordering step must make it clear when a consumer is taking on an obligation to pay, and businesses must set out the steps involved in placing the order. That is why a Join Waitlist form should not be quietly labelled or treated as a preorder." }] },
  { heading: "Does a Preorder Need a Delivery Date?", content: [{ type: "paragraph", text: "The retailer should provide meaningful information about expected supply. Current UK distance-selling guidance requires businesses to provide delivery arrangements and information about how long goods will take to arrive before an order is placed. It also states that goods should ordinarily be delivered within 30 days unless another timeframe has been agreed with the customer. This means a legitimate preorder can use a longer agreed timeframe where that is clearly established. The important point is that the later timeframe should be communicated and agreed rather than discovered after payment." }] },
  { heading: "What Is Made-to-Order Jewellery?", content: [{ type: "paragraph", text: "Made-to-order jewellery usually means a design is produced after an order is accepted rather than being taken from existing finished inventory. That does not automatically mean the piece is completely unique. A jeweller might repeatedly manufacture the same ring design but begin production only after a customer selects: metal; size; diamond specifications; or another approved variation. The result can still be a standard design. The important difference is the production model: ready-made = already manufactured; made to order = manufacturing begins after the order. That distinction affects lead time and what can be inspected before purchase." }] },
  { heading: "Made to Order Does Not Automatically Mean Custom", content: [{ type: "paragraph", text: "A standard necklace produced after the order is placed can be made to order without being uniquely customised. A ring engraved with a customer's initials or manufactured to one-off specifications may be personalised or custom-made. Those categories can have different commercial and cancellation consequences. Current UK returns guidance provides ordinary cancellation rights for eligible distance purchases but lists certain personalised or custom-made goods among exceptions. That does not mean every product manufactured after an order automatically loses ordinary cancellation rights. The actual nature of the product and transaction matters." }] },
  { heading: "What Is Custom or Bespoke Jewellery?", content: [{ type: "paragraph", text: "Custom or bespoke jewellery generally involves product decisions specific to the customer beyond selecting a normal stocked or standard option. That could include: unique design changes; special engraving; non-standard dimensions; or an individually commissioned design. However, businesses should use these terms carefully. Calling every standard ring produced after purchase \"bespoke\" can create confusion. The description should reflect what is actually being commissioned. For a buyer, ask: Am I choosing from standard options, or is the product being specifically altered or created for me?" }] },
  { content: [{ type: "image", src: "/images/blog/jewellery-availability-production-time/52 (2).jpg", alt: "Jewellery availability waitlist preorder made to order table comparison", title: "Waitlist vs Preorder vs Made to Order", caption: "These terms describe different commercial stages — a waitlist should register interest only, not create a payment obligation.", priority: false }] },
  { heading: "Waitlist vs Preorder vs Made to Order", content: [
    { type: "table", headers: ["Status", "What the customer is doing", "Has an order normally been created?", "Is production necessarily underway?"], rows: [["Waitlist", "Registering interest / asking to be notified", "No, unless explicitly established otherwise", "No"], ["Preorder", "Placing an order for future supply", "Yes", "Not necessarily"], ["Made to order", "Ordering a piece that will be manufactured after acceptance", "Yes", "Usually begins after the agreed order stage"], ["Custom / bespoke", "Commissioning a customer-specific version or design", "Usually", "Normally after specifications are agreed"], ["In stock", "Purchasing existing available inventory", "Yes when ordered", "Already produced"], ["Ready to ship", "Purchasing a finished item prepared for fulfilment", "Yes when ordered", "Production complete"]] },
    { type: "paragraph", text: "This table describes the normal commercial distinctions. A retailer's actual terms control the specific transaction." }
  ] },
  { heading: "A Waitlist Should Not Create a Payment Obligation", content: [{ type: "paragraph", text: "This is particularly important for Aurelia's current setup. If the client has not provided product prices and no direct checkout is available, Join Waitlist should remain a lead-generation action. The page or confirmation message can explain: Joining the waitlist registers your interest. It does not place an order or reserve a piece. Aurelia may contact you when further availability or ordering information is available. That wording is clear without making promises the business has not established. Do not display quantity selectors, an Add to Cart button or order-confirmation wording if the product cannot currently be purchased through the site." }] },
  { heading: "What Is Jewellery Production Time?", content: [{ type: "paragraph", text: "Production time is the period required to manufacture or prepare the jewellery before it can be dispatched. Depending on the actual product, that process could include: manufacturing; stone selection; setting; finishing; sizing; quality control; or other preparation. The critical concept is simply: production time ends before dispatch begins. It is not the same as delivery time." }] },
  { heading: "Production Time vs Dispatch Time vs Delivery Time", content: [{ type: "paragraph", text: "These terms should remain separate. Production time is the time required to create or prepare the product. Dispatch time concerns when the finished order leaves the retailer. Delivery or transit time concerns the carrier journey to the customer. Suppose a jewellery item has: 10 days of production; 1 day of dispatch processing; and 2 days of courier transit. Calling that simply: 2-day delivery would give the customer an inaccurate expectation. The same problem occurs when a retailer says: ships in two days when the jewellery itself takes several weeks to manufacture before the shipping stage begins. Use terms precisely." }] },
  { heading: "What Is a Jewellery Lead Time?", content: [{ type: "paragraph", text: "Lead time is often used to describe the overall period between an agreed order and the item being ready or supplied. But different businesses may use it differently. One company may use it for production only. Another may include production and dispatch. Another may mean estimated arrival. Therefore, if a product page uses the term: Lead time: 3–4 weeks it should explain what that period covers." }] },
  { heading: "What If You Need Jewellery for a Specific Date?", content: [{ type: "paragraph", text: "This is particularly important for: anniversaries; birthdays; weddings; proposals; graduations; or other fixed events. Do not calculate backwards using courier transit alone. First determine: whether the piece already exists; whether production is required; whether sizing or personalisation is required; when dispatch is expected; and: the estimated delivery window. Only then decide whether the timing works. If the event date is important, disclose it during the enquiry or ordering process and obtain a clear response. Do not assume that mentioning an event date automatically creates a contractual delivery guarantee." }] },
  { heading: "What Does \"Available Soon\" Mean?", content: [{ type: "paragraph", text: "On its own, not very much. \"Available soon\" can create uncertainty because it does not tell the customer: whether production has begun; whether orders are open; whether stock exists; or: when they can reasonably purchase the piece. If Aurelia does not yet have a confirmed availability date, clearer wording might be: Join the waitlist to register your interest and receive availability updates. That communicates what the visitor can actually do. Avoid false countdowns or artificial scarcity. The CMA has repeatedly warned businesses about misleading urgency claims, and its guidance covers claims such as countdown timers and scarcity messages that pressure consumers without a genuine basis." }] },
  { heading: "Should a Waitlist Have a Quantity Selector?", content: [{ type: "paragraph", text: "No, not in Aurelia's current enquiry-only setup. A quantity selector visually suggests a commerce transaction. If the user is merely registering interest in a product, asking them to choose Qty 1 / Qty 2 creates unnecessary confusion. Keep the action aligned with what actually happens." }] },
  { heading: "Should There Be an Add to Cart Button?", content: [{ type: "paragraph", text: "Not where the item cannot currently be purchased through an approved checkout. For Aurelia products without an approved selling price or direct purchasing mechanism: remove Add to Cart and quantity selection. Retain Wishlist functionality if desired. Use: Join Waitlist or: Enquire About This Piece. That accurately communicates the stage of the buyer journey." }] },
  { heading: "How Should Aurelia Describe the Current Waitlist?", content: [{ type: "paragraph", text: "Use wording along these lines: Join the Waitlist — Register your interest in this design and leave your email address. Aurelia may contact you when further availability or ordering information becomes available. Joining the waitlist does not place an order, reserve the jewellery or require payment. That is much safer than: Preorder Now if no preorder process exists. Or: Reserve Yours if no reservation actually occurs." }] },
  { heading: "What Should the Waitlist Confirmation Message Say?", content: [{ type: "paragraph", text: "A simple confirmation can state: Thank you. Your interest has been registered. We may contact you when further information about this design becomes available. This is not an order confirmation or reservation. That removes ambiguity at the exact point where misunderstanding could otherwise occur." }] },
  { heading: "Can You Cancel Made-to-Order Jewellery?", content: [{ type: "paragraph", text: "Do not assume the answer is always no. Current UK distance-selling rules generally provide cancellation rights for eligible online purchases, while certain goods made to the consumer's specifications or clearly personalised are exceptions. The critical distinction is that: made after the order does not automatically equal: made uniquely to the consumer's specifications. A standard repeatable design manufactured after an order and a uniquely engraved bespoke ring are not necessarily the same legal situation. Aurelia should therefore avoid blanket wording such as: All made-to-order pieces are non-refundable. Use only policy language that has been legally and commercially confirmed." }] },
  { heading: "How to Read a Jewellery Availability Page", content: [{ type: "paragraph", text: "When evaluating availability, ask four questions: Does the finished item currently exist? Can I place an actual order now? Will manufacturing begin only after I order? When should I reasonably expect dispatch or delivery? If the page does not answer those questions and timing matters to you, ask before committing." }] },
  { content: [{ type: "image", src: "/images/blog/jewellery-availability-production-time/52 (3).jpg", alt: "Jewellery availability examples in-stock made-to-order preorder waitlist Aurelia", title: "Availability Examples", caption: "Different availability stages create different expectations — know which stage you are entering before taking action.", priority: false }] },
  { heading: "Availability Examples", content: [{ type: "paragraph", text: "Example: In-Stock Ring. A ring already exists in the customer's required size. Process: available item → order → processing → dispatch → delivery. The relevant timing question is primarily fulfilment and delivery." }, { type: "paragraph", text: "Example: Made-to-Order Ring. The design is standard, but the ring will be produced only after the buyer chooses the required size and metal. Process becomes: order accepted → production → quality/preparation → dispatch → delivery. The customer needs to understand production time before relying on a delivery estimate." }, { type: "paragraph", text: "Example: Preorder Collection. A jewellery collection is scheduled for a future release, but the retailer accepts orders before that date. Process: preorder accepted → future stock/production → release → dispatch → delivery. Here the customer has actually ordered something. That is fundamentally different from a waitlist." }, { type: "paragraph", text: "Example: Aurelia Waitlist. For an Aurelia design that currently has no confirmed direct-purchase price or ordering mechanism: view design → join waitlist / submit enquiry → Aurelia may follow up → customer receives future information → customer decides whether to proceed. There is no automatic payment, order, reservation, or production stage created merely by submitting the email form. That distinction should appear consistently across the website." }] },
  { content: [{ type: "image", src: "/images/blog/jewellery-availability-production-time/52 (4).jpg", alt: "Jewellery availability production dispatch delivery timeline final answer", title: "The Complete Availability and Production Timeline", caption: "Availability → order → production → dispatch → delivery — know which stage applies to your product.", priority: false }] },
  { heading: "Frequently Asked Questions", content: [
    { type: "faq", title: "Frequently Asked Questions", items: [
      { question: "What does jewellery availability mean?", answer: "It describes the current commercial status of a piece—whether it already exists, can currently be ordered, requires production or is only open for future interest." },
      { question: "What does in stock mean?", answer: "It generally means inventory is currently available, although individual sizes or variations may still differ." },
      { question: "Does in stock mean immediate delivery?", answer: "No. Processing and shipping can still take time." },
      { question: "What does made to order mean?", answer: "It generally means the jewellery is produced after an order is accepted rather than supplied from existing finished stock." },
      { question: "Is made to order the same as bespoke?", answer: "No. A standard design can be manufactured after purchase without being unique or bespoke." },
      { question: "What is bespoke jewellery?", answer: "It generally refers to a product created or materially adapted to a customer's individual specification." },
      { question: "What is a jewellery waitlist?", answer: "It is usually a way to register interest and receive future availability information." },
      { question: "Does joining a waitlist place an order?", answer: "Not in Aurelia's proposed current setup. The email submission should register interest only." },
      { question: "Does joining Aurelia's waitlist reserve the jewellery?", answer: "No reservation should be claimed unless Aurelia creates an actual reservation system." },
      { question: "Is a waitlist the same as a preorder?", answer: "No." },
      { question: "What is a preorder?", answer: "A preorder normally means an actual order is accepted for future supply rather than immediate delivery." },
      { question: "What is production time?", answer: "It is the time needed to manufacture or prepare the jewellery before dispatch." },
      { question: "Is production time the same as delivery time?", answer: "No." },
      { question: "What is jewellery lead time?", answer: "It generally refers to the time needed before the item is ready or delivered, but sellers should define what their quoted lead time actually covers." },
      { question: "Does UK law require delivery within 30 days?", answer: "For distance sales, GOV.UK guidance states goods should ordinarily be delivered within 30 days unless another timeframe has been agreed with the customer." },
      { question: "Can made-to-order jewellery be cancelled?", answer: "Do not assume all made-to-order jewellery is automatically exempt from cancellation rights. Certain clearly personalised or customer-specification goods can be treated differently under UK distance-selling rules." },
      { question: "What if I need the jewellery for a wedding or anniversary?", answer: "Confirm the complete expected timeline before ordering and explain the required date to the retailer." },
      { question: "Should I count only shipping time?", answer: "No. If production is required, account for production, processing, dispatch and transit." },
      { question: "Does joining a waitlist start production?", answer: "No, not unless the retailer explicitly creates that system." },
      { question: "Should Aurelia use \"Preorder Now\" instead of \"Join Waitlist\"?", answer: "Not unless Aurelia is genuinely accepting orders for future supply and has the necessary pricing, payment, timing and terms in place." },
      { question: "Should Aurelia keep Add to Cart on products without prices?", answer: "No. If the item cannot currently be purchased, the interface should not imply that it can." },
      { question: "What CTA should Aurelia use?", answer: "For current products without an approved direct-purchase flow, use Join Waitlist and/or Enquire About This Piece." },
      { question: "What is the most important availability rule?", answer: "Know whether you are registering interest, placing an order or commissioning production before assuming that a product has been secured." }
    ]}
  ] },
  { heading: "Final Answer: How Should You Understand Jewellery Availability and Production Time?", content: [
    { type: "paragraph", text: "Start by identifying the product's actual status. If the finished item already exists, you are dealing primarily with order processing and delivery. If production starts only after the order, it is made to order. If you place an actual order now for future supply, it may be a preorder. If you only provide your email address because the product is not currently available for purchase, you are joining a waitlist. These terms should not be used interchangeably." },
    { type: "paragraph", text: "Then separate the timeline into: availability → order → production → dispatch → delivery. Some products skip the production stage because they already exist. Others may spend most of their lead time there. For any product needed by a specific date, confirm the entire timeframe rather than looking only at courier transit." },
    { type: "paragraph", text: "For Aurelia Royale, the current Join Waitlist or enquiry process should be treated only as an expression of interest where no approved purchase process exists. It should not imply: an order; a preorder; a reservation; payment; or: the start of production." },
    { type: "paragraph", parts: [{ text: "For the difference between existing and manufactured-after-order products, continue with " }, { text: "Ready-Made vs Made-to-Order Diamond Jewellery", href: "/blog/ready-made-vs-made-to-order-diamond-jewellery/" }] },
    { type: "paragraph", parts: [{ text: "For the overall online buying process, read " }, { text: "How to Buy Certified Lab-Grown Diamond Jewellery Online", href: "/blog/buy-certified-lab-grown-diamond-jewellery-online/" }] },
    { type: "paragraph", parts: [{ text: "Where an Aurelia design is not currently offered through an approved direct-purchase flow, " }, { text: "Join the Waitlist", href: "/contact/" }, { text: " or submit an enquiry to register your interest. Joining the waitlist should not be described as placing an order or reserving the product." }] },
    { type: "cta-banner", title: "Explore Aurelia Royale Lab-Grown Diamond Jewellery", subtitle: "Know which stage you are at — availability, interest, order or production.", shopHref: "/shop/", contactHref: "/contact/" }
  ] }
];
export default function BlogAvailabilityPage() {
  return (
    <main className="min-h-screen bg-background text-foreground font-sans overflow-x-clip">
      <section className="relative left-1/2 w-screen -translate-x-1/2 bg-[#e8e5dc] py-16">
        <div className="mx-auto max-w-4xl px-6 text-center">
          <span className="font-jost text-xs font-semibold uppercase tracking-[0.25em] text-gold">Lab-Grown Diamond Education</span>
          <h1 className="mt-4 font-cormorant text-5xl md:text-6xl font-medium leading-tight text-foreground uppercase tracking-wide">How to Understand Jewellery Availability and Production Time</h1>
          <p className="mt-6 font-jost text-sm font-light uppercase tracking-widest text-[#5a5a5a]">Waitlist, Preorder, Made-to-Order and Delivery Explained • Published September 10, 2026</p>
        </div>
      </section>
      <DynamicArticle sections={articleSections} />
      <RelatedArticles currentSlug="jewellery-availability-production-time" />
      <NewsletterSection />
    </main>
  );
}

