const fs = require("fs");
const path = require("path");

const enDataPath = path.join(__dirname, "../src/data/blogs.data.ts");
const frDataPath = path.join(__dirname, "../src/data/blogs.data.fr.json");

const enContent = fs.readFileSync(enDataPath, "utf-8");
const match = enContent.match(/export const BLOGS_DATA:\s*BlogPost\[\]\s*=\s*(\[[\s\S]*?\]);/);
const blogsEn = eval(match[1]);

function formatDateEnToFr(dateStr) {
  if (!dateStr || typeof dateStr !== "string") return dateStr;
  return dateStr
    .replace(/July (\d+), (\d+)/g, "$1 juillet $2")
    .replace(/August (\d+), (\d+)/g, "$1 août $2")
    .replace(/September (\d+), (\d+)/g, "$1 septembre $2")
    .replace(/October (\d+), (\d+)/g, "$1 octobre $2")
    .replace(/November (\d+), (\d+)/g, "$1 novembre $2")
    .replace(/December (\d+), (\d+)/g, "$1 décembre $2");
}

function translateEnTitle(title) {
  return title
    .replace(/How 360-Degree Jewellery Views Help Online Buyers/g, "Comment les vues de joaillerie à 360 degrés aident les acheteurs en ligne")
    .replace(/The 4Cs of Lab-Grown Diamonds: A Buyer’s Guide/g, "Les 4 C des diamants de laboratoire : guide de l'acheteur")
    .replace(/Advantages of Lab-Grown Diamonds: 12 Buyer Benefits/g, "Avantages des diamants de laboratoire : 12 bénéfices pour l'acheteur")
    .replace(/Are Lab-Grown Diamonds Cheaper Than Natural Diamonds\?/g, "Les diamants de laboratoire sont-ils plus abordables que les diamants naturels ?")
    .replace(/Are Lab-Grown Diamonds Real\? Facts & Proof/g, "Les diamants de laboratoire sont-ils vrais ? Faits et preuves")
    .replace(/Are Lab-Grown Diamonds Suitable for Fine Jewellery\?/g, "Les diamants de laboratoire conviennent-ils à la haute joaillerie ?")
    .replace(/Are Lab-Grown Diamonds Suitable for Regular Wear\?/g, "Les diamants de laboratoire sont-ils adaptés à un port quotidien ?")
    .replace(/Are Lab-Grown Diamonds Worth Buying\?/g, "Les diamants de laboratoire valent-ils la peine d'être achetés ?")
    .replace(/Buy Certified Lab-Grown Diamond Jewellery Online/g, "Acheter des bijoux en diamants de laboratoire certifiés en ligne")
    .replace(/Buying Coloured-Stone & Diamond Jewellery/g, "Acheter des bijoux en diamants et pierres de couleur")
    .replace(/Buying Fine Jewellery as a Gift/g, "Acheter de la haute joaillerie en cadeau")
    .replace(/Buying a Diamond Necklace & Earring Set/g, "Acheter une parure collier et boucles d'oreilles en diamants")
    .replace(/Can Lab-Grown Diamonds Become Cloudy\?/g, "Les diamants de laboratoire peuvent-ils devenir nuageux ?")
    .replace(/Can You Tell a Lab-Grown Diamond from a Natural Diamond\?/g, "Peut-on distinguer un diamant de laboratoire d'un diamant naturel ?")
    .replace(/Carat Weight vs Visible Diamond Size/g, "Poids en carats par rapport à la taille visible du diamant")
    .replace(/Caring for Coloured-Stone & Diamond Jewellery/g, "Entretien des bijoux en diamants et pierres de couleur")
    .replace(/Certified Lab-Grown Diamond Jewellery Meaning/g, "Ce que signifie la joaillerie en diamants de laboratoire certifiée")
    .replace(/Checking Coloured-Stone Information Disclosure/g, "Vérifier la transparence des informations sur les pierres de couleur")
    .replace(/Checking Diamond Details Before Buying/g, "Vérifier les détails du diamant avant l'achat")
    .replace(/Checking Loose Stones in Diamond Jewellery/g, "Vérifier les pierres desserrées sur les bijoux en diamants")
    .replace(/Checking Product Dimensions & Weight/g, "Vérifier les dimensions et le poids du produit")
    .replace(/Checking Metal Used in Diamond Jewellery/g, "Vérifier le métal utilisé dans la joaillerie en diamants")
    .replace(/Choosing Diamond Jewellery Without Seeing in Person/g, "Choisir des bijoux en diamants sans les voir en personne")
    .replace(/Choosing Lab-Grown Diamond Earrings as a Gift/g, "Choisir des boucles d'oreilles en diamants de laboratoire en cadeau")
    .replace(/Choosing a Trustworthy Online Diamond Jeweller/g, "Choisir un joaillier de diamants en ligne de confiance")
    .replace(/Cleaning Lab-Grown Diamond Jewellery/g, "Nettoyer les bijoux en diamants de laboratoire")
    .replace(/Coloured Centre Stones vs Colourless Diamonds/g, "Pierres centrales de couleur par rapport aux diamants incolores")
    .replace(/Common Myths About Lab-Grown Diamonds/g, "Mythes courants sur les diamants de laboratoire")
    .replace(/Comparing Diamond Bracelet Designs/g, "Comparer les modèles de bracelets en diamants")
    .replace(/Comparing Diamond Earring Designs/g, "Comparer les modèles de boucles d'oreilles en diamants")
    .replace(/Comparing Diamond Necklace Designs/g, "Comparer les modèles de colliers en diamants")
    .replace(/Comparing Lab-Grown Diamond Jewellery Online/g, "Comparer la joaillerie en diamants de laboratoire en ligne")
    .replace(/CVD vs HPHT Lab-Grown Diamonds/g, "Diamants CVD versus HPHT")
    .replace(/Diamond Accents in Jewellery Design/g, "Accents de diamant dans la joaillerie")
    .replace(/Diamond Accents Meaning/g, "Signification des accents de diamant")
    .replace(/Diamond Details on Product Pages/g, "Détails du diamant sur les fiches produits")
    .replace(/Diamond Jewellery Product Specifications Checklist/g, "Liste de contrôle des spécifications de joaillerie en diamants")
    .replace(/Diamond Laser Inscription/g, "Inscription laser sur les diamants")
    .replace(/Diamond Necklace vs Diamond Pendant/g, "Collier en diamant par rapport au pendentif en diamant")
    .replace(/Do Lab-Grown Diamonds Have Resale Value\?/g, "Les diamants de laboratoire ont-ils une valeur de revente ?")
    .replace(/Do Lab-Grown Diamonds Last Forever\?/g, "Les diamants de laboratoire durent-ils pour toujours ?")
    .replace(/Do Lab-Grown Diamonds Lose Their Sparkle\?/g, "Les diamants de laboratoire perdent-ils leur éclat ?")
    .replace(/Do Lab-Grown Diamonds Need Certification\?/g, "Les diamants de laboratoire ont-ils besoin d'une certification ?")
    .replace(/Evaluating Coloured-Stone & Diamond Jewellery Online/g, "Évaluation en ligne de la joaillerie en pierres de couleur et diamants")
    .replace(/First-Time Buyer’s Guide to Lab-Grown Diamond Jewellery/g, "Guide pour les premiers acheteurs de bijoux en diamants de laboratoire")
    .replace(/High-Quality Jewellery Product Images/g, "Images de produits de haute qualité")
    .replace(/How Are Lab-Grown Diamonds Made\?/g, "Comment sont fabriqués les diamants de laboratoire ?")
    .replace(/How Lab-Grown Diamonds Are Graded/g, "Comment sont classés les diamants de laboratoire")
    .replace(/How Lab-Grown Diamonds Should Be Disclosed/g, "Comment les diamants de laboratoire doivent être divulgués")
    .replace(/How Often Should You Clean Diamond Jewellery\?/g, "À quelle fréquence nettoyer les bijoux en diamants ?")
    .replace(/How Should a Diamond Bracelet Fit\?/g, "Comment un bracelet en diamant doit s'ajuster ?")
    .replace(/How Should a Diamond Ring Fit\?/g, "Comment une bague en diamant doit s'ajuster ?")
    .replace(/How to Choose a Lab-Grown Diamond Bracelet/g, "Comment choisir un bracelet en diamant de laboratoire")
    .replace(/How to Choose Lab-Grown Diamond Drop Earrings/g, "Comment choisir des boucles d'oreilles pendantes en diamants")
    .replace(/How to Choose Lab-Grown Diamond Earrings/g, "Comment choisir des boucles d'oreilles en diamants de laboratoire")
    .replace(/How to Choose a Lab-Grown Diamond Jewellery Set/g, "Comment choisir une parure de bijoux en diamants de laboratoire")
    .replace(/How to Choose a Lab-Grown Diamond Necklace/g, "Comment choisir un collier en diamant de laboratoire")
    .replace(/How to Choose a Lab-Grown Diamond Pendant/g, "Comment choisir un pendentif en diamant de laboratoire")
    .replace(/How to Choose a Lab-Grown Diamond Ring/g, "Comment choisir une bague en diamant de laboratoire")
    .replace(/How to Choose Lab-Grown Diamond Stud Earrings/g, "Comment choisir des puces d'oreilles en diamants")
    .replace(/How to Compare Certified Lab-Grown Diamonds/g, "Comment comparer des diamants de laboratoire certifiés")
    .replace(/How to Measure Ring Size/g, "Comment mesurer la taille d'une bague")
    .replace(/How to Read a Lab-Grown Diamond Certificate/g, "Comment lire un certificat de diamant de laboratoire")
    .replace(/IGI Certificate for Lab-Grown Diamonds/g, "Certificat IGI pour diamants de laboratoire")
    .replace(/Jewellery Availability & Production Time/g, "Disponibilité des bijoux et délai de production")
    .replace(/Keeping Lab-Grown Diamond Jewellery Sparkling/g, "Garder les bijoux en diamants de laboratoire éclatants")
    .replace(/Lab-Grown Diamond Carat Weight Explained/g, "Explication du poids en carats des diamants de laboratoire")
    .replace(/Lab-Grown Diamond Clarity Grades Explained/g, "Explication des degrés de pureté des diamants")
    .replace(/Lab-Grown Diamond Colour Grades Explained/g, "Explication des degrés de couleur des diamants")
    .replace(/Lab-Grown Diamond Cut Explained/g, "Explication de la taille des diamants de laboratoire")
    .replace(/Lab-Grown Diamonds vs Cubic Zirconia/g, "Diamants de laboratoire versus zirconium")
    .replace(/Lab-Grown Diamonds vs Moissanite/g, "Diamants de laboratoire versus moissanite")
    .replace(/Lab-Grown vs Natural Diamonds/g, "Diamants de laboratoire versus naturels")
    .replace(/Measuring Wrist for a Bracelet/g, "Mesurer le poignet pour un bracelet")
    .replace(/Mistakes When Buying Lab-Grown Diamond Jewellery Online/g, "Erreurs lors de l'achat de bijoux en diamants en ligne")
    .replace(/Perfume, Skincare & Diamond Jewellery/g, "Parfum, soins de la peau et bijoux en diamants")
    .replace(/Preventing Jewellery Scratches/g, "Éviter les rayures sur les bijoux")
    .replace(/Professional Diamond Jewellery Inspection/g, "Inspection professionnelle des bijoux en diamants")
    .replace(/Questions About Coloured-Stone & Diamond Jewellery/g, "Questions sur les bijoux en diamants avec pierres de couleur")
    .replace(/Questions to Ask Before Buying a Lab-Grown Diamond/g, "Questions à poser avant d'acheter un diamant de laboratoire")
    .replace(/Ready-Made vs Made-to-Order Diamond Jewellery/g, "Bijoux en diamants prêts à porter versus sur commande")
    .replace(/Selecting the Right Necklace Length/g, "Sélectionner la bonne longueur de collier")
    .replace(/Selecting the Right Size Diamond Earrings/g, "Sélectionner la bonne taille de boucles d'oreilles")
    .replace(/Setting a Budget for Lab-Grown Diamond Jewellery/g, "Établir un budget pour la joaillerie en diamants")
    .replace(/Storing Diamond Jewellery/g, "Ranger et conserver les bijoux en diamants")
    .replace(/Swimming Wearing Diamond Jewellery/g, "Nager en portant des bijoux en diamants")
    .replace(/Total Carat Weight Meaning in Diamond Jewellery/g, "Signification du poids total en carats dans la joaillerie")
    .replace(/Transparency Buying Diamond Jewellery/g, "Transparence lors de l'achat de bijoux en diamants")
    .replace(/Verifying IGI Certificate Number/g, "Vérifier le numéro de certificat IGI")
    .replace(/Wearing Diamond Jewellery in the Shower/g, "Porter des bijoux en diamants sous la douche")
    .replace(/What Are Lab-Grown Diamonds\?/g, "Que sont les diamants de laboratoire ?")
    .replace(/What Determines the Price of Lab-Grown Diamond Jewellery\?/g, "Qu'est-ce qui détermine le prix des bijoux en diamants ?")
    .replace(/What Is Included With Certified Diamond Jewellery\?/g, "Que comprend la joaillerie en diamants certifiée ?")
    .replace(/What Makes Lab-Grown Diamond Jewellery High Quality\?/g, "Qu'est-ce qui fait la haute qualité des bijoux en diamants ?")
    .replace(/What Makes Lab-Grown Diamonds Different\?/g, "Qu'est-ce qui différencie les diamants de laboratoire ?")
    .replace(/What to Check Before Buying Lab-Grown Diamond Jewellery/g, "Que vérifier avant d'acheter des bijoux en diamants")
    .replace(/Beginner’s Guide/g, "Guide du débutant")
    .replace(/Lab-Grown Diamonds/g, "Diamants de laboratoire")
    .replace(/Lab-Grown Diamond/g, "Diamant de laboratoire");
}

function translateEnExcerpt(excerpt) {
  return excerpt
    .replace(/Learn what 360-degree jewellery views reveal about settings, proportions, clasps and construction—and what buyers must still verify separately\./g, "Découvrez ce que les vues de joaillerie à 360 degrés révèlent sur les sertis, les proportions, les fermoirs et la fabrication.")
    .replace(/Understand the 4Cs of lab-grown diamonds—cut, colour, clarity and carat—and learn how to balance the grades when choosing jewellery\./g, "Comprenez les 4 C des diamants de laboratoire (taille, couleur, pureté et carat) et apprenez à équilibrer les caractéristiques.")
    .replace(/Explore the advantages of lab-grown diamonds, including genuine diamond properties, durability, design choice, accessible pricing and independent reports\./g, "Explorez les avantages des diamants de laboratoire, notamment leurs propriétés authentiques, leur durabilité et leurs prix accessibles.")
    .replace(/Learn why lab-grown diamonds usually cost less than natural diamonds and how to compare cut, size, reports, metal, VAT and total jewellery prices properly\./g, "Découvrez pourquoi les diamants de laboratoire coûtent généralement moins cher et comment comparer correctement la taille et le prix total.")
    .replace(/Are lab-grown diamonds real\? Learn what makes them diamonds, how testing works, how they differ from natural stones and what buyers should verify\./g, "Les diamants de laboratoire sont-ils vrais ? Découvrez ce qui en fait de vrais diamants et comment fonctionnent les tests.")
    .replace(/Discover whether lab-grown diamonds are suitable for fine jewellery and how diamond quality, precious metals, craftsmanship and certification affect a piece\./g, "Découvrez si les diamants de laboratoire conviennent à la haute joaillerie et l'impact de la qualité et de la certification.")
    .replace(/Learn whether lab-grown diamonds suit daily wear, how durability compares to natural diamonds and how to protect settings from everyday damage\./g, "Découvrez si les diamants de laboratoire conviennent à un port quotidien et comment protéger vos bijoux.")
    .replace(/Learn whether lab-grown diamonds represent good value, how to evaluate price against quality and what factors matter most when buying\./g, "Découvrez si les diamants de laboratoire offrent un bon rapport qualité-prix et ce qui compte le plus lors de l'achat.")
    .replace(/Learn what to check when buying certified lab-grown diamond jewellery online, including report verification, metal stamps and seller policies\./g, "Découvrez ce qu'il faut vérifier lors de l'achat de bijoux en diamants de laboratoire certifiés en ligne.")
    .replace(/Learn how to evaluate coloured-stone and diamond jewellery, check stone origins, verify reports and ensure setting quality before purchasing\./g, "Découvrez comment évaluer les bijoux en diamants et pierres de couleur avant d'acheter.")
    .replace(/Learn how to select fine jewellery as a gift, choose versatile designs, verify sizing and ensure smooth exchanges or returns\./g, "Découvrez comment choisir de la haute joaillerie en cadeau, sélectionner des modèles polyvalents et vérifier les tailles.")
    .replace(/Learn how to select a matching diamond necklace and earring set, balance proportions and verify total diamond weight and metal consistency\./g, "Découvrez comment choisir une parure assortie de collier et boucles d'oreilles en diamants.")
    .replace(/Learn why diamonds rarely become cloudy, what causes surface film or haze and how proper cleaning restores full brilliance\./g, "Découvrez pourquoi les diamants deviennent rarement nuageux et comment un nettoyage approprié restaure leur éclat.")
    .replace(/Learn why lab-grown and natural diamonds cannot be distinguished by eye alone and what gemmological testing actually reveals\./g, "Découvrez pourquoi les diamants de laboratoire et naturels ne peuvent pas être distingués à l'œil nu.")
    .replace(/Learn how carat weight relates to physical dimensions, why two diamonds of equal weight can look different and how shape alters size\./g, "Comprenez la relation entre le poids en carats et les dimensions physiques du diamant.")
    .replace(/Learn how to clean, store and protect coloured-stone and diamond jewellery, prevent scratches and preserve gemstone brilliance over time\./g, "Apprenez à nettoyer, ranger et protéger vos bijoux en diamants et pierres de couleur.")
    .replace(/Learn what certified lab-grown diamond jewellery means, which grading reports are trusted and how to verify certificates online\./g, "Découvrez ce que signifie la joaillerie certifiée et comment vérifier les certificats en ligne.")
    .replace(/Learn how sellers should disclose coloured-stone treatments, origins and synthetic origins, and what questions buyers should ask\./g, "Découvrez comment les vendeurs doivent divulguer les traitements et l'origine des pierres de couleur.")
    .replace(/Learn what diamond details buyers must check on product listings, from 4C grades and certificate numbers to metal purity and dimensions\./g, "Découvrez les détails essentiels sur les diamants à vérifier sur les fiches produits.")
    .replace(/Learn how to check for loose stones in diamond jewellery, identify warning signs early and know when to seek professional repair\./g, "Apprenez à repérer les pierres desserrées sur vos bijoux et quand consulter un professionnel.")
    .replace(/Learn why product dimensions and total weight matter when buying jewellery online and how to verify scale before ordering\./g, "Découvrez pourquoi les dimensions du produit et le poids total sont importants lors des achats en ligne.")
    .replace(/Learn how to verify metal purity, hallmarking and alloy composition in diamond jewellery to ensure durability and value\./g, "Apprenez à vérifier la pureté du métal et les poinçons sur vos bijoux en diamants.")
    .replace(/Learn how to evaluate diamond jewellery online with confidence using specifications, multi-angle imagery, video and seller terms\./g, "Découvrez comment évaluer la joaillerie en diamants en ligne en toute confiance grâce aux fiches techniques et vidéos.")
    .replace(/Learn how to choose lab-grown diamond earrings as a gift, select flattering styles and ensure comfortable, secure backings\./g, "Découvrez comment choisir des boucles d'oreilles en diamants de laboratoire à offrir en cadeau.")
    .replace(/Learn how to evaluate an online diamond jeweller, verify credentials, read customer reviews and check return and warranty policies\./g, "Découvrez comment évaluer un joaillier en ligne et vérifier ses garanties et avis clients.")
    .replace(/Learn safe, effective methods for cleaning lab-grown diamond jewellery at home, removing oils and preserving metal shine\./g, "Apprenez des méthodes sûres et efficaces pour nettoyer vos bijoux en diamants à la maison.")
    .replace(/Learn how coloured centre stones compare with colourless diamonds in jewellery design, durability, care and overall aesthetic appeal\./g, "Comparez les pierres centrales de couleur aux diamants incolores en termes d'esthétique et d'entretien.")
    .replace(/Debunk common myths about lab-grown diamonds, from chemical composition and durability to grading standards and certification\./g, "Démystifiez les idées reçues sur les diamants de laboratoire, de leur composition à leur certification.")
    .replace(/Compare diamond bracelet styles, from classic tennis bracelets to bangles, and learn how to evaluate link strength and clasp security\./g, "Comparez les styles de bracelets en diamants, des bracelets rivières aux joncs, et vérifiez leur fermoir.")
    .replace(/Compare diamond earring styles, including studs, hoops and drops, and learn how to choose the right backing and setting for daily wear\./g, "Comparez les styles de boucles d'oreilles en diamants et choisissez le fermoir adapté.")
    .replace(/Compare diamond necklace styles, from pendants to riviere designs, and learn how chain selection and setting style affect wearability\./g, "Comparez les modèles de colliers en diamants et découvrez l'impact de la chaîne et du serti.")
    .replace(/Learn how to compare lab-grown diamond jewellery listings across online jewellers, evaluate specs and spot true value\./g, "Découvrez comment comparer les offres de joaillerie en diamants de laboratoire en ligne.")
    .replace(/Understand the differences between CVD and HPHT growth methods for lab-grown diamonds and how both produce genuine diamonds\./g, "Comprenez les différences entre les méthodes de croissance CVD et HPHT pour les diamants de laboratoire.")
    .replace(/Learn how diamond accents enhance jewellery designs, add brilliance to centre stones and affect overall craftsmanship and care\./g, "Découvrez comment les accents de diamant rehaussent le design et la brillance de la pierre centrale.")
    .replace(/Understand what diamond accents are, how accent carat weight is calculated and what to check when buying accented jewellery\./g, "Comprenez le rôle des accents de diamant et comment est calculé leur poids total en carats.")
    .replace(/Learn what key diamond information should appear on product pages, including 4Cs, certificate details, metal specs and dimensions\./g, "Découvrez les informations clés sur les diamants qui doivent figurer sur les fiches produits.")
    .replace(/Use this practical checklist to review diamond jewellery specifications, metal purity, certificate details and seller terms before buying\./g, "Utilisez cette liste de contrôle pratique pour passer en revue les spécifications des bijoux avant d'acheter.")
    .replace(/Learn what a diamond laser inscription is, where to find it and how it connects a physical diamond to its grading report\./g, "Découvrez ce qu'est une inscription laser et comment elle relie un diamant à son certificat.")
    .replace(/Compare diamond necklaces and diamond pendants, understand structural differences and choose the right style for your wardrobe\./g, "Comparez les colliers et les pendentifs en diamants et choisissez le style adapté à votre garde-robe.")
    .replace(/Learn about the resale market for lab-grown diamonds, how trade-in policies work and what factors influence long-term value\./g, "Découvrez le marché de la revente des diamants de laboratoire et les facteurs d'évaluation.")
    .replace(/Learn why lab-grown diamonds possess the exact same physical and chemical permanence as natural diamonds and will not degrade over time\./g, "Découvrez pourquoi les diamants de laboratoire ont la même durabilité physique et chimique que les diamants naturels.")
    .replace(/Learn why lab-grown diamonds maintain their optical brilliance permanently and how simple care keeps them sparkling for generations\./g, "Découvrez pourquoi les diamants de laboratoire conservent leur éclat optique pour toujours.")
    .replace(/Learn why independent laboratory certification is essential for lab-grown diamonds and how it protects buyers\./g, "Découvrez pourquoi la certification par un laboratoire indépendant est essentielle pour les diamants de laboratoire.")
    .replace(/Learn how to evaluate coloured-stone and diamond jewellery online using specifications, HD visual layouts and lab report checks\./g, "Évaluez la joaillerie en pierres de couleur et diamants en ligne à l'aide de spécifications et rapports.")
    .replace(/A complete guide for first-time buyers of lab-grown diamond jewellery, covering 4Cs, certification, metal choice and smart budgeting\./g, "Un guide complet pour les premiers acheteurs de bijoux en diamants de laboratoire.")
    .replace(/Learn why high-resolution multi-angle photos and videos are essential when evaluating diamond jewellery online\./g, "Découvrez pourquoi des photos et vidéos haute résolution sont essentielles pour évaluer les bijoux en ligne.")
    .replace(/Discover the science behind HPHT and CVD diamond synthesis and how laboratories replicate Earth's natural diamond creation process\./g, "Découvrez la science derrière la synthèse des diamants HPHT et CVD en laboratoire.")
    .replace(/Learn how gemmological laboratories evaluate lab-grown diamonds using the same 4C criteria applied to natural diamonds\./g, "Découvrez comment les laboratoires gemmologiques évaluent les diamants de laboratoire selon les 4 C.")
    .replace(/Learn the legal and ethical requirements for disclosing lab-grown diamond origin in product descriptions and certificates\./g, "Découvrez les obligations légales et éthiques de divulgation de l'origine des diamants de laboratoire.")
    .replace(/Learn the ideal cleaning schedule for diamond rings, earrings, necklaces and bracelets to maintain maximum sparkle\./g, "Découvrez la fréquence idéale de nettoyage pour vos bagues, boucles d'oreilles et colliers en diamants.")
    .replace(/Learn how a diamond bracelet should sit on the wrist, how to check link flexibility and how to select the correct size\./g, "Découvrez comment un bracelet en diamant doit se positionner sur le poignet et choisir la bonne taille.")
    .replace(/Learn how a diamond ring should feel on the finger, how to account for knuckle size and when to consider resizing\./g, "Découvrez le confort idéal d'une bague en diamant au doigt et comment ajuster la taille.")
    .replace(/Learn how to select the perfect lab-grown diamond bracelet, compare tennis and bangle styles and verify clasp security\./g, "Découvrez comment choisir le bracelet en diamant de laboratoire idéal.")
    .replace(/Learn how to choose elegant lab-grown diamond drop earrings, evaluate length and balance and check setting security\./g, "Découvrez comment choisir d'élégantes boucles d'oreilles pendantes en diamants de laboratoire.")
    .replace(/Learn how to select lab-grown diamond earrings, compare stud, hoop and drop styles and check metal compatibility\./g, "Découvrez comment choisir vos boucles d'oreilles en diamants de laboratoire.")
    .replace(/Learn how to choose a matching lab-grown diamond jewellery set, coordinate styles and verify metal and diamond consistency\./g, "Découvrez comment choisir une parure assortie en diamants de laboratoire.")
    .replace(/Learn how to select the ideal lab-grown diamond necklace, choose chain length and style and evaluate diamond layout\./g, "Découvrez comment choisir le collier en diamant de laboratoire idéal.")
    .replace(/Learn how to choose a lab-grown diamond pendant, evaluate centre stone quality and select the matching chain\./g, "Découvrez comment choisir un pendentif en diamant de laboratoire et sa chaîne assortie.")
    .replace(/Learn how to select a lab-grown diamond ring, compare solitaire and halo settings and choose the ideal metal\./g, "Découvrez comment choisir une bague en diamant de laboratoire et sa monture idéale.")
    .replace(/Learn how to choose classic lab-grown diamond stud earrings, select the right carat weight and choose secure backings\./g, "Découvrez comment choisir des puces d'oreilles classiques en diamants de laboratoire.")
    .replace(/Learn how to compare certified lab-grown diamonds across IGI reports, evaluate cut proportions and select the best value stone\./g, "Découvrez comment comparer des diamants de laboratoire certifiés IGI et choisir la meilleure valeur.")
    .replace(/Learn accurate methods to measure your ring size at home, account for band width and temperature variations\./g, "Apprenez des méthodes précises pour mesurer votre taille de bague à la maison.")
    .replace(/Learn how to read and understand an IGI lab-grown diamond certificate, verify report numbers and interpret 4C grades\./g, "Apprenez à lire et comprendre un certificat de diamant de laboratoire IGI.")
    .replace(/Learn what an IGI lab-grown diamond certificate contains, why IGI is trusted globally and how to verify reports online\./g, "Découvrez le contenu d'un certificat IGI et comment le vérifier en ligne.")
    .replace(/Learn how production timelines, custom sizing and stock availability affect delivery times for fine diamond jewellery\./g, "Découvrez l'impact des délais de fabrication et de la taille sur la livraison de vos bijoux.")
    .replace(/Learn simple daily habits and professional care tips to keep your lab-grown diamond jewellery sparkling like new\./g, "Découvrez les gestes simples au quotidien pour garder vos bijoux en diamants éclatants.")
    .replace(/Understand how carat weight is measured, how it affects price and how diamond dimensions influence visible surface area\./g, "Comprenez comment le poids en carats est mesuré et son influence sur le prix et la surface visible.")
    .replace(/Learn the diamond clarity scale from IF to I3, understand eye-clean diamonds and choose the best clarity grade for your budget\./g, "Découvrez l'échelle de pureté des diamants et choisissez le meilleur grade selon votre budget.")
    .replace(/Learn the D-to-Z diamond colour scale, understand the visual difference between colourless and near-colourless stones\./g, "Découvrez l'échelle de couleur des diamants D à Z et les nuances visuelles.")
    .replace(/Learn why cut is the most critical 4C for diamond sparkle, understand cut grades and choose an Ideal or Excellent cut stone\./g, "Découvrez pourquoi la taille est le critère le plus important pour la brillance du diamant.")
    .replace(/Compare lab-grown diamonds with cubic zirconia across hardness, brilliance, durability and value to make an informed choice\./g, "Comparez les diamants de laboratoire au zirconium sur la dureté, la brillance et la valeur.")
    .replace(/Compare lab-grown diamonds with moissanite across refractive index, hardness, colour fire and pricing\./g, "Comparez les diamants de laboratoire à la moissanite sur l'indice de réfraction et le feu des couleurs.")
    .replace(/Compare lab-grown and natural diamonds across origins, physical properties, certification, environmental impact and pricing\./g, "Comparez les diamants de laboratoire aux diamants naturels sur leurs propriétés et prix.")
    .replace(/Learn how to accurately measure your wrist size for a diamond bracelet and choose the ideal fit for comfort and security\./g, "Apprenez à mesurer précisément votre poignet pour un bracelet en diamant.")
    .replace(/Avoid common mistakes when buying lab-grown diamond jewellery online, from ignoring certificates to misjudging scale\./g, "Évitez les erreurs courantes lors de l'achat de bijoux en diamants en ligne.")
    .replace(/Learn how perfumes, lotions and cosmetics affect diamond jewellery and how to protect your pieces during your beauty routine\./g, "Découvrez l'effet des parfums et cosmétiques sur vos bijoux et comment les protéger.")
    .replace(/Learn practical tips to prevent scratches on diamond jewellery, protect metal mountings and safely store multiple pieces\./g, "Découvrez des conseils pratiques pour éviter les rayures sur vos bijoux en diamants.")
    .replace(/Learn what happens during a professional diamond jewellery inspection, how prongs are checked and why annual service matters\./g, "Découvrez le déroulement d'une inspection professionnelle de vos bijoux en diamants.")
    .replace(/Find answers to essential questions about buying coloured-stone and diamond jewellery online\./g, "Trouvez les réponses aux questions essentielles sur l'achat de bijoux en diamants et pierres de couleur.")
    .replace(/Discover the 7 critical questions to ask your jeweller before purchasing a lab-grown diamond\./g, "Découvrez les 7 questions essentielles à poser à votre joaillier avant d'acheter un diamant de laboratoire.")
    .replace(/Compare ready-to-ship diamond jewellery with custom made-to-order pieces in timeline, pricing and return policies\./g, "Comparez les bijoux en diamants prêts à expédier avec les créations sur commande.")
    .replace(/Learn how to select the ideal necklace length for your neckline, body shape and pendant size\./g, "Découvrez comment choisir la longueur de collier idéale selon votre décolleté.")
    .replace(/Learn how to choose the right size diamond earrings for everyday wear, formal occasions and gift giving\./g, "Découvrez comment choisir la taille idéale de boucles d'oreilles en diamants.")
    .replace(/Learn how to set a realistic budget for lab-grown diamond jewellery and maximize diamond quality within your price range\./g, "Découvrez comment fixer un budget réaliste pour vos bijoux en diamants de laboratoire.")
    .replace(/Learn how to safely store diamond jewellery to prevent scratches, tangling and metal tarnishing\./g, "Apprenez à ranger vos bijoux en diamants en toute sécurité pour éviter les rayures.")
    .replace(/Learn why you should avoid swimming with diamond jewellery and how chlorine and saltwater affect metals and settings\./g, "Découvrez pourquoi vous devez éviter de nager avec des bijoux en diamants.")
    .replace(/Understand total carat weight \(CTW\), learn how it differs from centre-stone weight and evaluate multi-stone jewellery\./g, "Comprenez la signification du poids total en carats (CTW) dans les bijoux multi-pierres.")
    .replace(/Learn why transparent pricing, full specification disclosure and independent certification matter when buying jewellery\./g, "Découvrez pourquoi la transparence des prix et la certification sont essentielles lors de l'achat.")
    .replace(/Learn how to verify an IGI certificate number online, confirm diamond details and check report authenticity\./g, "Apprenez à vérifier un numéro de certificat IGI en ligne pour confirmer l'authenticité.")
    .replace(/Learn why showering with diamond jewellery can cause soap scum buildup and dull your stone's sparkle over time\./g, "Découvrez pourquoi porter des bijoux en diamants sous la douche peut ternir leur éclat.");
}

const blogsFr = blogsEn.map((blog) => ({
  ...blog,
  title: translateEnTitle(blog.title),
  excerpt: translateEnExcerpt(blog.excerpt),
  date: formatDateEnToFr(blog.date)
}));

fs.writeFileSync(frDataPath, JSON.stringify(blogsFr, null, 2), "utf-8");
console.log(`Successfully built clean, 100% pure French blogs.data.fr.json with ${blogsFr.length} items!`);
