import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

type LockPackage = {
    version?: string;
    peerDependencies?: Record<string, string>;
    peerDependenciesMeta?: Record<string, { optional?: boolean }>;
};

const lock = JSON.parse(
    readFileSync(join(process.cwd(), "package-lock.json"), "utf8"),
) as { packages: Record<string, LockPackage> };

const parse = (version: string) =>
    version.split(".").map((part) => Number.parseInt(part, 10));

/** True when `version` is >= `min`. Enough for the x.y.z values in a lockfile. */
function atLeast(version: string, min: string) {
    const [a, b, c] = parse(version);
    const [x, y, z] = parse(min);
    if (a !== x) return a > x;
    if (b !== y) return b > y;
    return c >= z;
}

/**
 * Guards an AWS Amplify deploy failure that no local command reproduced.
 *
 * `@swc/helpers` is an OPTIONAL peer of `@swc/core` (pulled in by next-intl)
 * wanting >=0.5.17, while `next` depends on it pinned exactly to 0.5.15. One
 * copy cannot satisfy both, and the two npm generations disagree about what to
 * do:
 *
 *   npm 11 — skips the optional peer, writes no nested entry.
 *   npm 10 — installs a nested copy, and `npm ci` hard-fails without it:
 *            "npm error `npm ci` can only install packages when your
 *             package.json and package-lock.json ... are in sync.
 *             Missing: @swc/helpers@0.5.23 from lock file"
 *
 * Amplify runs the npm 10 resolution, so a lock regenerated by npm 11 builds
 * fine on every developer machine and then breaks the deploy. A lock that
 * carries the nested entry satisfies BOTH: npm 10 needs it, npm 11 ignores the
 * extra. Verified against `npm ci` on 9, 10 and 11.
 *
 * If this fails, the lock was regenerated with a newer npm. Restore the entry
 * with:  npx npm@10 install --package-lock-only
 */
describe("package-lock npm-version compatibility", () => {
    const MIN_PEER = "0.5.17";

    const swcCorePresent = Object.keys(lock.packages).some((path) =>
        path.endsWith("node_modules/@swc/core"),
    );

    it("still has an @swc/core that declares the conflicting optional peer", () => {
        // If this ever goes false the guard below is obsolete, and the comment
        // above should be deleted rather than the test quietly passing forever.
        expect(swcCorePresent).toBe(true);
    });

    it("carries an @swc/helpers copy satisfying @swc/core's peer range", () => {
        const satisfying = Object.entries(lock.packages).filter(
            ([path, meta]) =>
                path.endsWith("node_modules/@swc/helpers") &&
                meta.version &&
                atLeast(meta.version, MIN_PEER),
        );

        expect(
            satisfying.length,
            `No @swc/helpers >= ${MIN_PEER} in package-lock.json. npm 10 — which ` +
                "Amplify uses — will fail `npm ci`. Run: npx npm@10 install --package-lock-only",
        ).toBeGreaterThan(0);
    });

    it("keeps the exact copy next pins, so next is not silently upgraded", () => {
        const root = lock.packages["node_modules/@swc/helpers"];
        expect(root?.version).toBe("0.5.15");
    });
});
